import Donnees from "./pages/LesUtilisateurs";

const DONNEES = [
  {
    "index": "6a86698be963b5d7e952ac95",
    "picture": "/avatars/townsend-barrett.jpg",
    "age": 27,
    "firstName": "Arnaud",
    "lastName": "Moukouaga",
    "gender": "male",
    "email": "townsendbarrett@virva.com",
    "phone": "+242 (897) 545-2132",
    "address": "Deseret, Utah",
    "about": "consequat id voluptate minim proident duis aliqua tempor exercitation eiusmod aliqua reprehenderit quis minim amet sint velit cillum ut labore"
  },
  {
    "index": "6a86698be4651e33d005f913",
    "picture": "/avatars/santos-aguilar.jpg",
    "age": 31,
    "firstName": "Serge",
    "lastName": "Mba",
    "gender": "male",
    "email": "santosaguilar@virva.com",
    "phone": "+242 (826) 493-3458",
    "address": "Fivepointville, Kansas",
    "about": "proident veniam tempor officia mollit magna proident ipsum nisi aute occaecat reprehenderit minim consectetur ut consequat ipsum veniam et aliqua"
  },
  {
    "index": "6a86698bb35d2b1b3c49657d",
    "picture": "/avatars/terra-strong.jpg",
    "age": 28,
    "firstName": "Estelle",
    "lastName": "Obiang",
    "gender": "female",
    "email": "terrastrong@virva.com",
    "phone": "+242 (960) 434-2166",
    "address": "Longoria, Connecticut",
    "about": "enim qui ullamco aliqua voluptate anim laboris culpa occaecat officia voluptate magna pariatur in est commodo voluptate proident irure magna"
  },
  {
    "index": "6a86698b4af3a4487ff60ab4",
    "picture": "/avatars/madge-henson.jpg",
    "age": 35,
    "firstName": "Nadine",
    "lastName": "Moussavou",
    "gender": "female",
    "email": "madgehenson@virva.com",
    "phone": "+242 (988) 589-3875",
    "address": "Rivera, Washington",
    "about": "enim tempor ipsum excepteur ex id consequat laboris consectetur culpa non do veniam anim quis irure ad irure officia in"
  },
  {
    "index": "6a86698bedfe6ffb596e772d",
    "picture": "/avatars/ray-daniel.jpg",
    "age": 37,
    "firstName": "Fabrice",
    "lastName": "Ondo",
    "gender": "male",
    "email": "raydaniel@virva.com",
    "phone": "+242 (892) 590-3233",
    "address": "Taycheedah, Nevada",
    "about": "velit non cillum qui do cillum aute officia est deserunt consectetur quis dolore reprehenderit Lorem nostrud nulla sunt officia excepteur"
  },
  {
    "index": "6a86698b1bb156a315ef6844",
    "picture": "/avatars/alisa-ortega.jpg",
    "age": 32,
    "firstName": "Audrey",
    "lastName": "Mounguengui",
    "gender": "female",
    "email": "alisaortega@virva.com",
    "phone": "+242 (847) 600-3874",
    "address": "Grandview, Georgia",
    "about": "sit incididunt tempor velit ut commodo ut dolore in qui ipsum sint dolor voluptate deserunt ut aliqua enim cupidatat velit"
  },
  {
    "index": "6a86698bb8989b00dcd1bccc",
    "picture": "/avatars/cleo-figueroa.jpg",
    "age": 20,
    "firstName": "Carine",
    "lastName": "Nzigou",
    "gender": "female",
    "email": "cleofigueroa@virva.com",
    "phone": "+242 (968) 414-2304",
    "address": "Johnsonburg, Guam",
    "about": "sunt esse dolor reprehenderit laborum enim ea sit aute ut duis exercitation laboris quis minim dolore reprehenderit duis deserunt Lorem"
  },
  {
    "index": "6a86698b2326435cc2a6c4b4",
    "picture": "/avatars/reid-cameron.jpg",
    "age": 44,
    "firstName": "Thierry",
    "lastName": "Ndong",
    "gender": "male",
    "email": "reidcameron@virva.com",
    "phone": "+242 (832) 486-3041",
    "address": "Loma, Illinois",
    "about": "exercitation esse occaecat deserunt ea fugiat id cupidatat incididunt elit labore aliqua amet excepteur irure amet minim magna reprehenderit in"
  },
  {
    "index": "6a86698b1c72bb0c24fdfe11",
    "picture": "/avatars/tasha-joyce.jpg",
    "age": 34,
    "firstName": "Grace",
    "lastName": "Okemba",
    "gender": "female",
    "email": "tashajoyce@virva.com",
    "phone": "+242 (814) 553-2699",
    "address": "Lorraine, New Mexico",
    "about": "cillum aliqua anim enim id minim occaecat minim id sunt cillum id eu duis ut in velit enim occaecat nulla"
  },
  {
    "index": "6a86698b8f9d61afde685b82",
    "picture": "/avatars/carrie-allen.jpg",
    "age": 19,
    "firstName": "Chantal",
    "lastName": "Mabiala",
    "gender": "female",
    "email": "carrieallen@virva.com",
    "phone": "+242 (803) 430-3734",
    "address": "Chloride, Florida",
    "about": "laboris proident ex et qui consequat aliqua sint fugiat fugiat magna tempor nostrud magna deserunt ut ea veniam anim sint"
  },
  {
    "index": "6a86698bf07046953d4a241c",
    "picture": "/avatars/lola-pate.jpg",
    "age": 26,
    "firstName": "Blandine",
    "lastName": "Nkouka",
    "gender": "female",
    "email": "lolapate@virva.com",
    "phone": "+242 (929) 482-2081",
    "address": "Orin, North Dakota",
    "about": "ullamco do ullamco sunt dolore et occaecat voluptate eu culpa tempor consectetur cillum anim est ex eu eu excepteur adipisicing"
  },
  {
    "index": "6a86698b560672db8ebd5680",
    "picture": "/avatars/lillie-barton.jpg",
    "age": 32,
    "firstName": "Mireille",
    "lastName": "Mpassi",
    "gender": "female",
    "email": "lilliebarton@virva.com",
    "phone": "+242 (987) 579-3911",
    "address": "Cartwright, District Of Columbia",
    "about": "veniam voluptate enim nostrud dolor eu nulla in consectetur nisi magna esse ad ipsum qui Lorem do Lorem id quis"
  },
  {
    "index": "6a86698b5fb1378f7f8a6cc0",
    "picture": "/avatars/koch-maxwell.jpg",
    "age": 22,
    "firstName": "Ghislain",
    "lastName": "Ngouabi",
    "gender": "male",
    "email": "kochmaxwell@virva.com",
    "phone": "+242 (873) 454-3018",
    "address": "Finzel, Texas",
    "about": "deserunt eiusmod adipisicing dolore aute in consectetur quis nisi et magna labore in occaecat elit ullamco amet anim quis veniam"
  },
  {
    "index": "6a86698b50fdcf611a9b6f3e",
    "picture": "/avatars/nunez-turner.jpg",
    "age": 28,
    "firstName": "Brice",
    "lastName": "Massamba",
    "gender": "male",
    "email": "nunezturner@virva.com",
    "phone": "+242 (851) 436-3296",
    "address": "Brantleyville, Puerto Rico",
    "about": "eiusmod dolore veniam adipisicing aliqua mollit veniam consequat minim adipisicing magna aliquip ea aute exercitation sint sunt officia et labore"
  },
  {
    "index": "6a86698b9709d16c0ce521a9",
    "picture": "/avatars/short-larsen.jpg",
    "age": 29,
    "firstName": "Wilfried",
    "lastName": "Moungani",
    "gender": "male",
    "email": "shortlarsen@virva.com",
    "phone": "+242 (808) 489-2762",
    "address": "Brutus, Louisiana",
    "about": "nulla in labore ea consequat cupidatat commodo ad exercitation consectetur mollit cillum laborum tempor sit consectetur laboris qui exercitation ullamco"
  },
  {
    "index": "6a86698b45894befc3bf8eb1",
    "picture": "/avatars/hooper-rojas.jpg",
    "age": 18,
    "firstName": "Cedric",
    "lastName": "Ngoma",
    "gender": "male",
    "email": "hooperrojas@virva.com",
    "phone": "+242 (845) 566-2088",
    "address": "Rivereno, Delaware",
    "about": "enim eiusmod aute in ullamco et voluptate veniam veniam id aliquip anim enim sunt in et anim magna qui culpa"
  },
  {
    "index": "6a86698bee4cb73de726b767",
    "picture": "/avatars/deena-stevenson.jpg",
    "age": 35,
    "firstName": "Bintou",
    "lastName": "Coulibaly",
    "gender": "female",
    "email": "deenastevenson@virva.com",
    "phone": "+242 (829) 467-2108",
    "address": "Kimmell, New Jersey",
    "about": "culpa tempor dolore ad sunt dolore aute in dolore nisi eu ad consectetur ea non officia id incididunt enim labore"
  },
  {
    "index": "6a86698b2a22db03cbf333ff",
    "picture": "/avatars/enid-boyle.jpg",
    "age": 21,
    "firstName": "Mariam",
    "lastName": "Kone",
    "gender": "female",
    "email": "enidboyle@virva.com",
    "phone": "+242 (958) 513-3149",
    "address": "Unionville, Virgin Islands",
    "about": "quis ex elit deserunt est incididunt ullamco occaecat incididunt commodo aute ex incididunt officia sint laborum voluptate consectetur aliqua in"
  },
  {
    "index": "6a86698b84fea96609f6db42",
    "picture": "/avatars/wise-velazquez.jpg",
    "age": 44,
    "firstName": "Abdoulaye",
    "lastName": "Sarr",
    "gender": "male",
    "email": "wisevelazquez@virva.com",
    "phone": "+242 (802) 477-2841",
    "address": "Rodanthe, Ohio",
    "about": "esse reprehenderit aute qui sint velit ut deserunt ullamco id excepteur non esse dolor et officia sit laborum id incididunt"
  },
  {
    "index": "6a86698bae522c9350f640d6",
    "picture": "/avatars/delacruz-johns.jpg",
    "age": 34,
    "firstName": "Seydou",
    "lastName": "Keita",
    "gender": "male",
    "email": "delacruzjohns@virva.com",
    "phone": "+242 (893) 436-3951",
    "address": "Cuylerville, Iowa",
    "about": "non commodo nisi irure cillum nostrud nisi sunt deserunt occaecat reprehenderit magna amet nulla adipisicing tempor ea anim veniam ex"
  },
  {
    "index": "6a86698bb731d2af52ccd9c1",
    "picture": "/avatars/patrica-horn.jpg",
    "age": 26,
    "firstName": "Oumou",
    "lastName": "Sangare",
    "gender": "female",
    "email": "patricahorn@virva.com",
    "phone": "+242 (822) 430-2650",
    "address": "Worton, Oregon",
    "about": "nisi sunt Lorem ad magna sunt culpa culpa id anim magna in et laborum exercitation dolor id qui adipisicing laborum"
  },
  {
    "index": "6a86698b0477c2fd92dc0e52",
    "picture": "/avatars/morrison-kinney.jpg",
    "age": 30,
    "firstName": "Bakary",
    "lastName": "Coulibaly",
    "gender": "male",
    "email": "morrisonkinney@virva.com",
    "phone": "+242 (834) 525-3029",
    "address": "Canoochee, Minnesota",
    "about": "nulla aliquip anim duis eu adipisicing Lorem aliqua excepteur ea eiusmod nulla magna mollit minim culpa do dolor adipisicing excepteur"
  },
  {
    "index": "6a86698ba47f8933d35bc23f",
    "picture": "/avatars/collier-burgess.jpg",
    "age": 28,
    "firstName": "Idrissa",
    "lastName": "Camara",
    "gender": "male",
    "email": "collierburgess@virva.com",
    "phone": "+242 (855) 573-2698",
    "address": "Walton, Virginia",
    "about": "quis irure cupidatat ut elit est sint veniam et dolore eu esse pariatur adipisicing cupidatat nulla do enim irure minim"
  },
  {
    "index": "6a86698b843eb06e757fbf04",
    "picture": "/avatars/marietta-dunn.jpg",
    "age": 43,
    "firstName": "Rokhaya",
    "lastName": "Fall",
    "gender": "female",
    "email": "mariettadunn@virva.com",
    "phone": "+242 (840) 410-2485",
    "address": "Ypsilanti, Montana",
    "about": "cillum qui laborum magna culpa deserunt incididunt qui sunt anim Lorem ex Lorem ullamco minim mollit dolore labore officia commodo"
  },
  {
    "index": "6a86698bee17a594fff58fc4",
    "picture": "/avatars/opal-moreno.jpg",
    "age": 25,
    "firstName": "Ndeye",
    "lastName": "Sarr",
    "gender": "female",
    "email": "opalmoreno@virva.com",
    "phone": "+242 (833) 516-3471",
    "address": "Leyner, Northern Mariana Islands",
    "about": "irure esse tempor id consectetur ipsum sint deserunt nulla excepteur ex anim dolor adipisicing ex in labore mollit nulla consequat"
  },
  {
    "index": "6a86698b9ae60b8e985e7998",
    "picture": "/avatars/oconnor-lindsey.jpg",
    "age": 25,
    "firstName": "Lamine",
    "lastName": "Fall",
    "gender": "male",
    "email": "oconnorlindsey@virva.com",
    "phone": "+242 (843) 465-2158",
    "address": "Highland, South Dakota",
    "about": "sint cillum aliquip ea quis sunt officia excepteur duis amet fugiat nostrud ea dolor quis occaecat incididunt sint voluptate culpa"
  },
  {
    "index": "6a86698bf6d3fea1efd8b99f",
    "picture": "/avatars/lottie-chavez.jpg",
    "age": 38,
    "firstName": "Abena",
    "lastName": "Mensah",
    "gender": "female",
    "email": "lottiechavez@virva.com",
    "phone": "+242 (867) 582-3396",
    "address": "Spelter, West Virginia",
    "about": "laborum sunt pariatur ut sint aliquip aute labore ullamco sit consectetur in qui aliquip mollit sunt ipsum labore labore officia"
  },
  {
    "index": "6a86698b3a191e372e652323",
    "picture": "/avatars/gallagher-hood.jpg",
    "age": 28,
    "firstName": "Souleymane",
    "lastName": "Toure",
    "gender": "male",
    "email": "gallagherhood@virva.com",
    "phone": "+242 (801) 579-2232",
    "address": "Catharine, Maine",
    "about": "labore nulla eu occaecat sint consectetur excepteur sunt eu dolor duis occaecat officia culpa commodo cillum ullamco officia anim velit"
  },
  {
    "index": "6a86698b108612570c5c148c",
    "picture": "/avatars/lilly-carr.jpg",
    "age": 33,
    "firstName": "Akua",
    "lastName": "Boateng",
    "gender": "female",
    "email": "lillycarr@virva.com",
    "phone": "+242 (857) 581-2771",
    "address": "Whitehaven, Oklahoma",
    "about": "velit ex quis veniam occaecat magna sunt ut mollit dolore ullamco excepteur qui consectetur ex amet veniam nostrud occaecat cillum"
  },
  {
    "index": "6a86698b616a3b36c2e9e75b",
    "picture": "/avatars/wagner-slater.jpg",
    "age": 32,
    "firstName": "Boubacar",
    "lastName": "Barry",
    "gender": "male",
    "email": "wagnerslater@virva.com",
    "phone": "+242 (887) 470-3825",
    "address": "Columbus, South Carolina",
    "about": "elit deserunt id commodo eu dolor dolore duis nisi pariatur laboris ullamco qui labore proident deserunt commodo quis laboris in"
  },
  {
    "index": "6a86698b8ef8ed307f95e7ed",
    "picture": "/avatars/brewer-sheppard.jpg",
    "age": 41,
    "firstName": "Samba",
    "lastName": "Seck",
    "gender": "male",
    "email": "brewersheppard@virva.com",
    "phone": "+242 (956) 439-2469",
    "address": "Campo, Wisconsin",
    "about": "labore minim laborum magna in do exercitation aute aliqua reprehenderit exercitation reprehenderit ea magna minim magna qui aliqua sit cillum"
  },
  {
    "index": "6a86698b4fd9ee5c9b0fe555",
    "picture": "/avatars/randolph-bauer.jpg",
    "age": 44,
    "firstName": "Modou",
    "lastName": "Faye",
    "gender": "male",
    "email": "randolphbauer@virva.com",
    "phone": "+242 (822) 421-2006",
    "address": "Frizzleburg, Missouri",
    "about": "anim in elit ex consectetur officia proident laboris pariatur cupidatat excepteur ad sunt dolor sunt nostrud minim aliquip sit minim"
  },
  {
    "index": "6a86698b4867a7204dfdfdcf",
    "picture": "/avatars/grimes-eaton.jpg",
    "age": 19,
    "firstName": "Youssouf",
    "lastName": "Kone",
    "gender": "male",
    "email": "grimeseaton@virva.com",
    "phone": "+242 (969) 455-3716",
    "address": "Caledonia, Wyoming",
    "about": "eu sint ipsum tempor sint anim mollit sint ullamco laborum esse cupidatat ipsum id velit minim eu et nisi laborum"
  },
  {
    "index": "6a86698bbe58a576f09c89e2",
    "picture": "/avatars/madeleine-preston.jpg",
    "age": 44,
    "firstName": "Adwoa",
    "lastName": "Owusu",
    "gender": "female",
    "email": "madeleinepreston@virva.com",
    "phone": "+242 (953) 554-2395",
    "address": "Davenport, Alabama",
    "about": "veniam laborum voluptate ea dolore fugiat mollit eiusmod id mollit occaecat proident ut occaecat qui fugiat ullamco officia occaecat elit"
  },
  {
    "index": "6a86698b401a621a7d238eb6",
    "picture": "/avatars/claire-stephenson.jpg",
    "age": 26,
    "firstName": "Chiamaka",
    "lastName": "Okafor",
    "gender": "female",
    "email": "clairestephenson@virva.com",
    "phone": "+242 (809) 583-3526",
    "address": "Stewart, Arizona",
    "about": "duis pariatur ut et incididunt aute veniam enim culpa mollit non ut velit minim anim nulla sint dolore veniam ea"
  },
  {
    "index": "6a86698ba1f8391c844f0e79",
    "picture": "/avatars/salinas-dudley.jpg",
    "age": 26,
    "firstName": "Issa",
    "lastName": "Sanogo",
    "gender": "male",
    "email": "salinasdudley@virva.com",
    "phone": "+242 (935) 562-3145",
    "address": "Yukon, Indiana",
    "about": "et deserunt eiusmod velit quis aliquip dolore enim eiusmod tempor ex ea labore elit qui sunt anim ea laborum laboris"
  },
  {
    "index": "6a86698b7b403b455cb77dc1",
    "picture": "/avatars/farmer-navarro.jpg",
    "age": 43,
    "firstName": "Lassana",
    "lastName": "Diarra",
    "gender": "male",
    "email": "farmernavarro@virva.com",
    "phone": "+242 (991) 404-2709",
    "address": "Downsville, Kentucky",
    "about": "duis anim et velit id excepteur ut eu irure tempor esse ad mollit duis anim labore amet et aliqua mollit"
  },
  {
    "index": "6a86698b18e14ce8a02b0272",
    "picture": "/avatars/marguerite-dominguez.jpg",
    "age": 33,
    "firstName": "Ngozi",
    "lastName": "Obi",
    "gender": "female",
    "email": "margueritedominguez@virva.com",
    "phone": "+242 (977) 522-3002",
    "address": "Romeville, Federated States Of Micronesia",
    "about": "qui est commodo Lorem aute mollit culpa voluptate proident sunt duis cupidatat minim sint do magna irure Lorem cillum nulla"
  },
  {
    "index": "6a86698b50069cc43ebdea73",
    "picture": "/avatars/molly-salazar.jpg",
    "age": 19,
    "firstName": "Nneka",
    "lastName": "Nwosu",
    "gender": "female",
    "email": "mollysalazar@virva.com",
    "phone": "+242 (839) 576-3273",
    "address": "Brule, Michigan",
    "about": "aliquip commodo est exercitation exercitation consequat commodo dolor ut pariatur aute aute excepteur officia aliquip mollit duis laboris occaecat anim"
  },
  {
    "index": "6a86698b4ad52ee7d57a71f7",
    "picture": "/avatars/bowman-bradford.jpg",
    "age": 33,
    "firstName": "Chinedu",
    "lastName": "Okafor",
    "gender": "male",
    "email": "bowmanbradford@virva.com",
    "phone": "+242 (838) 528-3844",
    "address": "Chestnut, Alaska",
    "about": "incididunt commodo proident cillum laboris irure deserunt laboris et nulla fugiat magna pariatur quis sit incididunt cupidatat nulla fugiat dolor"
  },
  {
    "index": "6a86698b715423a2f1289016",
    "picture": "/avatars/atkins-maynard.jpg",
    "age": 19,
    "firstName": "Emeka",
    "lastName": "Obi",
    "gender": "male",
    "email": "atkinsmaynard@virva.com",
    "phone": "+242 (902) 435-2413",
    "address": "Beaulieu, Marshall Islands",
    "about": "enim sit fugiat dolor est aute sunt duis aliqua cillum adipisicing eiusmod dolore commodo commodo irure nostrud mollit ea culpa"
  },
  {
    "index": "6a86698b9314becdbc60abc6",
    "picture": "/avatars/darla-todd.jpg",
    "age": 31,
    "firstName": "Zanele",
    "lastName": "Mokoena",
    "gender": "female",
    "email": "darlatodd@virva.com",
    "phone": "+242 (948) 532-3331",
    "address": "Stonybrook, Idaho",
    "about": "culpa minim tempor est nulla velit commodo minim laborum laboris magna in consequat cupidatat magna Lorem occaecat ex et sunt"
  },
  {
    "index": "6a86698bc9fcf716a277f142",
    "picture": "/avatars/karina-mcdaniel.jpg",
    "age": 36,
    "firstName": "Nomsa",
    "lastName": "Dlamini",
    "gender": "female",
    "email": "karinamcdaniel@virva.com",
    "phone": "+242 (860) 587-3121",
    "address": "Esmont, North Carolina",
    "about": "deserunt aute velit do ex qui minim id eiusmod laboris voluptate irure tempor ut culpa non nulla ex laborum labore"
  },
  {
    "index": "6a86698b9e948119e66c3304",
    "picture": "/avatars/kramer-ray.jpg",
    "age": 28,
    "firstName": "Chukwudi",
    "lastName": "Nwosu",
    "gender": "male",
    "email": "kramerray@virva.com",
    "phone": "+242 (947) 505-3699",
    "address": "Southmont, California",
    "about": "cupidatat nulla aute nostrud Lorem do nostrud nisi laboris ad dolore ullamco sunt fugiat do occaecat mollit aute cupidatat laboris"
  },
  {
    "index": "6a86698b0416da11ca2de93f",
    "picture": "/avatars/calderon-rhodes.jpg",
    "age": 38,
    "firstName": "Femi",
    "lastName": "Adeyemi",
    "gender": "male",
    "email": "calderonrhodes@virva.com",
    "phone": "+242 (886) 448-3504",
    "address": "Nash, New York",
    "about": "exercitation amet tempor sint est est sunt cupidatat reprehenderit veniam ut duis ut est qui nulla anim aliqua id minim"
  },
  {
    "index": "6a86698b89f4da9f16bf0d1d",
    "picture": "/avatars/tucker-rodgers.jpg",
    "age": 20,
    "firstName": "Olumide",
    "lastName": "Adebayo",
    "gender": "male",
    "email": "tuckerrodgers@virva.com",
    "phone": "+242 (875) 515-2971",
    "address": "Worcester, Mississippi",
    "about": "consectetur nulla duis nostrud nisi in nisi tempor fugiat dolore nulla voluptate proident aliquip magna tempor duis nisi id consequat"
  },
  {
    "index": "6a86698be22f175372140094",
    "picture": "/avatars/yates-walters.jpg",
    "age": 37,
    "firstName": "Thabo",
    "lastName": "Mokoena",
    "gender": "male",
    "email": "yateswalters@virva.com",
    "phone": "+242 (823) 468-2372",
    "address": "Blue, Rhode Island",
    "about": "enim sit labore magna et pariatur cupidatat id exercitation irure nisi culpa anim laboris id nisi aute voluptate aliqua culpa"
  },
  {
    "index": "6a86698b27aaa7fc0f01b49e",
    "picture": "/avatars/dotson-hahn.jpg",
    "age": 20,
    "firstName": "Sipho",
    "lastName": "Dlamini",
    "gender": "male",
    "email": "dotsonhahn@virva.com",
    "phone": "+242 (930) 456-2381",
    "address": "Brandermill, Hawaii",
    "about": "culpa anim aute officia nostrud exercitation nostrud aute dolor velit qui officia id aliquip fugiat minim ipsum dolore excepteur aute"
  },
  {
    "index": "6a86698bf61a5ac0fafde18d",
    "picture": "/avatars/cooke-duke.jpg",
    "age": 34,
    "firstName": "Bongani",
    "lastName": "Nkosi",
    "gender": "male",
    "email": "cookeduke@virva.com",
    "phone": "+242 (837) 554-2457",
    "address": "Hayden, Maryland",
    "about": "dolor do aliqua ad adipisicing reprehenderit adipisicing tempor sint anim pariatur quis eiusmod quis ullamco commodo eiusmod laborum tempor officia"
  },
  {
    "index": "6a86698bdeb777190b2ae452",
    "picture": "/avatars/robles-cervantes.jpg",
    "age": 36,
    "firstName": "Themba",
    "lastName": "Ndlovu",
    "gender": "male",
    "email": "roblescervantes@virva.com",
    "phone": "+242 (983) 466-2478",
    "address": "Tyhee, Vermont",
    "about": "ut voluptate irure tempor do et qui commodo adipisicing fugiat id exercitation deserunt tempor in adipisicing nulla consectetur fugiat officia"
  }
];
console.log(DONNEES[0]);

function App() {
  return (
    <section>
      <Donnees donnees={DONNEES} />
    </section>
  );
}

export default App;
